/*
 * Decompiled with CFR 0.0.
 * 
 * Could not load the following classes:
 *  android.text.TextUtils
 *  java.lang.CharSequence
 *  java.lang.Enum
 *  java.lang.Object
 *  java.lang.String
 */
package app.dukhaan.src.java.io.branch.referral.util;

import android.text.TextUtils;

public final class CurrencyType
extends Enum<CurrencyType> {
    private static final /* synthetic */ CurrencyType[] $VALUES;
    public static final /* enum */ CurrencyType AED;
    public static final /* enum */ CurrencyType AFN;
    public static final /* enum */ CurrencyType ALL;
    public static final /* enum */ CurrencyType AMD;
    public static final /* enum */ CurrencyType ANG;
    public static final /* enum */ CurrencyType AOA;
    public static final /* enum */ CurrencyType ARS;
    public static final /* enum */ CurrencyType AUD;
    public static final /* enum */ CurrencyType AWG;
    public static final /* enum */ CurrencyType AZN;
    public static final /* enum */ CurrencyType BAM;
    public static final /* enum */ CurrencyType BBD;
    public static final /* enum */ CurrencyType BDT;
    public static final /* enum */ CurrencyType BGN;
    public static final /* enum */ CurrencyType BHD;
    public static final /* enum */ CurrencyType BIF;
    public static final /* enum */ CurrencyType BMD;
    public static final /* enum */ CurrencyType BND;
    public static final /* enum */ CurrencyType BOB;
    public static final /* enum */ CurrencyType BOV;
    public static final /* enum */ CurrencyType BRL;
    public static final /* enum */ CurrencyType BSD;
    public static final /* enum */ CurrencyType BTN;
    public static final /* enum */ CurrencyType BWP;
    public static final /* enum */ CurrencyType BYN;
    public static final /* enum */ CurrencyType BYR;
    public static final /* enum */ CurrencyType BZD;
    public static final /* enum */ CurrencyType CAD;
    public static final /* enum */ CurrencyType CDF;
    public static final /* enum */ CurrencyType CHE;
    public static final /* enum */ CurrencyType CHF;
    public static final /* enum */ CurrencyType CHW;
    public static final /* enum */ CurrencyType CLF;
    public static final /* enum */ CurrencyType CLP;
    public static final /* enum */ CurrencyType CNY;
    public static final /* enum */ CurrencyType COP;
    public static final /* enum */ CurrencyType COU;
    public static final /* enum */ CurrencyType CRC;
    public static final /* enum */ CurrencyType CUC;
    public static final /* enum */ CurrencyType CUP;
    public static final /* enum */ CurrencyType CVE;
    public static final /* enum */ CurrencyType CZK;
    public static final /* enum */ CurrencyType DJF;
    public static final /* enum */ CurrencyType DKK;
    public static final /* enum */ CurrencyType DOP;
    public static final /* enum */ CurrencyType DZD;
    public static final /* enum */ CurrencyType EGP;
    public static final /* enum */ CurrencyType ERN;
    public static final /* enum */ CurrencyType ETB;
    public static final /* enum */ CurrencyType EUR;
    public static final /* enum */ CurrencyType FJD;
    public static final /* enum */ CurrencyType FKP;
    public static final /* enum */ CurrencyType GBP;
    public static final /* enum */ CurrencyType GEL;
    public static final /* enum */ CurrencyType GHS;
    public static final /* enum */ CurrencyType GIP;
    public static final /* enum */ CurrencyType GMD;
    public static final /* enum */ CurrencyType GNF;
    public static final /* enum */ CurrencyType GTQ;
    public static final /* enum */ CurrencyType GYD;
    public static final /* enum */ CurrencyType HKD;
    public static final /* enum */ CurrencyType HNL;
    public static final /* enum */ CurrencyType HRK;
    public static final /* enum */ CurrencyType HTG;
    public static final /* enum */ CurrencyType HUF;
    public static final /* enum */ CurrencyType IDR;
    public static final /* enum */ CurrencyType ILS;
    public static final /* enum */ CurrencyType INR;
    public static final /* enum */ CurrencyType IQD;
    public static final /* enum */ CurrencyType IRR;
    public static final /* enum */ CurrencyType ISK;
    public static final /* enum */ CurrencyType JMD;
    public static final /* enum */ CurrencyType JOD;
    public static final /* enum */ CurrencyType JPY;
    public static final /* enum */ CurrencyType KES;
    public static final /* enum */ CurrencyType KGS;
    public static final /* enum */ CurrencyType KHR;
    public static final /* enum */ CurrencyType KMF;
    public static final /* enum */ CurrencyType KPW;
    public static final /* enum */ CurrencyType KRW;
    public static final /* enum */ CurrencyType KWD;
    public static final /* enum */ CurrencyType KYD;
    public static final /* enum */ CurrencyType KZT;
    public static final /* enum */ CurrencyType LAK;
    public static final /* enum */ CurrencyType LBP;
    public static final /* enum */ CurrencyType LKR;
    public static final /* enum */ CurrencyType LRD;
    public static final /* enum */ CurrencyType LSL;
    public static final /* enum */ CurrencyType LYD;
    public static final /* enum */ CurrencyType MAD;
    public static final /* enum */ CurrencyType MDL;
    public static final /* enum */ CurrencyType MGA;
    public static final /* enum */ CurrencyType MKD;
    public static final /* enum */ CurrencyType MMK;
    public static final /* enum */ CurrencyType MNT;
    public static final /* enum */ CurrencyType MOP;
    public static final /* enum */ CurrencyType MRO;
    public static final /* enum */ CurrencyType MUR;
    public static final /* enum */ CurrencyType MVR;
    public static final /* enum */ CurrencyType MWK;
    public static final /* enum */ CurrencyType MXN;
    public static final /* enum */ CurrencyType MXV;
    public static final /* enum */ CurrencyType MYR;
    public static final /* enum */ CurrencyType MZN;
    public static final /* enum */ CurrencyType NAD;
    public static final /* enum */ CurrencyType NGN;
    public static final /* enum */ CurrencyType NIO;
    public static final /* enum */ CurrencyType NOK;
    public static final /* enum */ CurrencyType NPR;
    public static final /* enum */ CurrencyType NZD;
    public static final /* enum */ CurrencyType OMR;
    public static final /* enum */ CurrencyType PAB;
    public static final /* enum */ CurrencyType PEN;
    public static final /* enum */ CurrencyType PGK;
    public static final /* enum */ CurrencyType PHP;
    public static final /* enum */ CurrencyType PKR;
    public static final /* enum */ CurrencyType PLN;
    public static final /* enum */ CurrencyType PYG;
    public static final /* enum */ CurrencyType QAR;
    public static final /* enum */ CurrencyType RON;
    public static final /* enum */ CurrencyType RSD;
    public static final /* enum */ CurrencyType RUB;
    public static final /* enum */ CurrencyType RWF;
    public static final /* enum */ CurrencyType SAR;
    public static final /* enum */ CurrencyType SBD;
    public static final /* enum */ CurrencyType SCR;
    public static final /* enum */ CurrencyType SDG;
    public static final /* enum */ CurrencyType SEK;
    public static final /* enum */ CurrencyType SGD;
    public static final /* enum */ CurrencyType SHP;
    public static final /* enum */ CurrencyType SLL;
    public static final /* enum */ CurrencyType SOS;
    public static final /* enum */ CurrencyType SRD;
    public static final /* enum */ CurrencyType SSP;
    public static final /* enum */ CurrencyType STD;
    public static final /* enum */ CurrencyType SYP;
    public static final /* enum */ CurrencyType SZL;
    public static final /* enum */ CurrencyType THB;
    public static final /* enum */ CurrencyType TJS;
    public static final /* enum */ CurrencyType TMT;
    public static final /* enum */ CurrencyType TND;
    public static final /* enum */ CurrencyType TOP;
    public static final /* enum */ CurrencyType TRY;
    public static final /* enum */ CurrencyType TTD;
    public static final /* enum */ CurrencyType TWD;
    public static final /* enum */ CurrencyType TZS;
    public static final /* enum */ CurrencyType UAH;
    public static final /* enum */ CurrencyType UGX;
    public static final /* enum */ CurrencyType USD;
    public static final /* enum */ CurrencyType USN;
    public static final /* enum */ CurrencyType UYI;
    public static final /* enum */ CurrencyType UYU;
    public static final /* enum */ CurrencyType UZS;
    public static final /* enum */ CurrencyType VEF;
    public static final /* enum */ CurrencyType VND;
    public static final /* enum */ CurrencyType VUV;
    public static final /* enum */ CurrencyType WST;
    public static final /* enum */ CurrencyType XAF;
    public static final /* enum */ CurrencyType XAG;
    public static final /* enum */ CurrencyType XAU;
    public static final /* enum */ CurrencyType XBA;
    public static final /* enum */ CurrencyType XBB;
    public static final /* enum */ CurrencyType XBC;
    public static final /* enum */ CurrencyType XBD;
    public static final /* enum */ CurrencyType XCD;
    public static final /* enum */ CurrencyType XDR;
    public static final /* enum */ CurrencyType XFU;
    public static final /* enum */ CurrencyType XOF;
    public static final /* enum */ CurrencyType XPD;
    public static final /* enum */ CurrencyType XPF;
    public static final /* enum */ CurrencyType XPT;
    public static final /* enum */ CurrencyType XSU;
    public static final /* enum */ CurrencyType XTS;
    public static final /* enum */ CurrencyType XUA;
    public static final /* enum */ CurrencyType XXX;
    public static final /* enum */ CurrencyType YER;
    public static final /* enum */ CurrencyType ZAR;
    public static final /* enum */ CurrencyType ZMW;
    private String iso4217Code = "";

    static {
        CurrencyType currencyType;
        AED = new CurrencyType("AED");
        AFN = new CurrencyType("AFN");
        ALL = new CurrencyType("ALL");
        AMD = new CurrencyType("AMD");
        ANG = new CurrencyType("ANG");
        AOA = new CurrencyType("AOA");
        ARS = new CurrencyType("ARS");
        AUD = new CurrencyType("AUD");
        AWG = new CurrencyType("AWG");
        AZN = new CurrencyType("AZN");
        BAM = new CurrencyType("BAM");
        BBD = new CurrencyType("BBD");
        BDT = new CurrencyType("BDT");
        BGN = new CurrencyType("BGN");
        BHD = new CurrencyType("BHD");
        BIF = new CurrencyType("BIF");
        BMD = new CurrencyType("BMD");
        BND = new CurrencyType("BND");
        BOB = new CurrencyType("BOB");
        BOV = new CurrencyType("BOV");
        BRL = new CurrencyType("BRL");
        BSD = new CurrencyType("BSD");
        BTN = new CurrencyType("BTN");
        BWP = new CurrencyType("BWP");
        BYN = new CurrencyType("BYN");
        BYR = new CurrencyType("BYR");
        BZD = new CurrencyType("BZD");
        CAD = new CurrencyType("CAD");
        CDF = new CurrencyType("CDF");
        CHE = new CurrencyType("CHE");
        CHF = new CurrencyType("CHF");
        CHW = new CurrencyType("CHW");
        CLF = new CurrencyType("CLF");
        CLP = new CurrencyType("CLP");
        CNY = new CurrencyType("CNY");
        COP = new CurrencyType("COP");
        COU = new CurrencyType("COU");
        CRC = new CurrencyType("CRC");
        CUC = new CurrencyType("CUC");
        CUP = new CurrencyType("CUP");
        CVE = new CurrencyType("CVE");
        CZK = new CurrencyType("CZK");
        DJF = new CurrencyType("DJF");
        DKK = new CurrencyType("DKK");
        DOP = new CurrencyType("DOP");
        DZD = new CurrencyType("DZD");
        EGP = new CurrencyType("EGP");
        ERN = new CurrencyType("ERN");
        ETB = new CurrencyType("ETB");
        EUR = new CurrencyType("EUR");
        FJD = new CurrencyType("FJD");
        FKP = new CurrencyType("FKP");
        GBP = new CurrencyType("GBP");
        GEL = new CurrencyType("GEL");
        GHS = new CurrencyType("GHS");
        GIP = new CurrencyType("GIP");
        GMD = new CurrencyType("GMD");
        GNF = new CurrencyType("GNF");
        GTQ = new CurrencyType("GTQ");
        GYD = new CurrencyType("GYD");
        HKD = new CurrencyType("HKD");
        HNL = new CurrencyType("HNL");
        HRK = new CurrencyType("HRK");
        HTG = new CurrencyType("HTG");
        HUF = new CurrencyType("HUF");
        IDR = new CurrencyType("IDR");
        ILS = new CurrencyType("ILS");
        INR = new CurrencyType("INR");
        IQD = new CurrencyType("IQD");
        IRR = new CurrencyType("IRR");
        ISK = new CurrencyType("ISK");
        JMD = new CurrencyType("JMD");
        JOD = new CurrencyType("JOD");
        JPY = new CurrencyType("JPY");
        KES = new CurrencyType("KES");
        KGS = new CurrencyType("KGS");
        KHR = new CurrencyType("KHR");
        KMF = new CurrencyType("KMF");
        KPW = new CurrencyType("KPW");
        KRW = new CurrencyType("KRW");
        KWD = new CurrencyType("KWD");
        KYD = new CurrencyType("KYD");
        KZT = new CurrencyType("KZT");
        LAK = new CurrencyType("LAK");
        LBP = new CurrencyType("LBP");
        LKR = new CurrencyType("LKR");
        LRD = new CurrencyType("LRD");
        LSL = new CurrencyType("LSL");
        LYD = new CurrencyType("LYD");
        MAD = new CurrencyType("MAD");
        MDL = new CurrencyType("MDL");
        MGA = new CurrencyType("MGA");
        MKD = new CurrencyType("MKD");
        MMK = new CurrencyType("MMK");
        MNT = new CurrencyType("MNT");
        MOP = new CurrencyType("MOP");
        MRO = new CurrencyType("MRO");
        MUR = new CurrencyType("MUR");
        MVR = new CurrencyType("MVR");
        MWK = new CurrencyType("MWK");
        MXN = new CurrencyType("MXN");
        MXV = new CurrencyType("MXV");
        MYR = new CurrencyType("MYR");
        MZN = new CurrencyType("MZN");
        NAD = new CurrencyType("NAD");
        NGN = new CurrencyType("NGN");
        NIO = new CurrencyType("NIO");
        NOK = new CurrencyType("NOK");
        NPR = new CurrencyType("NPR");
        NZD = new CurrencyType("NZD");
        OMR = new CurrencyType("OMR");
        PAB = new CurrencyType("PAB");
        PEN = new CurrencyType("PEN");
        PGK = new CurrencyType("PGK");
        PHP = new CurrencyType("PHP");
        PKR = new CurrencyType("PKR");
        PLN = new CurrencyType("PLN");
        PYG = new CurrencyType("PYG");
        QAR = new CurrencyType("QAR");
        RON = new CurrencyType("RON");
        RSD = new CurrencyType("RSD");
        RUB = new CurrencyType("RUB");
        RWF = new CurrencyType("RWF");
        SAR = new CurrencyType("SAR");
        SBD = new CurrencyType("SBD");
        SCR = new CurrencyType("SCR");
        SDG = new CurrencyType("SDG");
        SEK = new CurrencyType("SEK");
        SGD = new CurrencyType("SGD");
        SHP = new CurrencyType("SHP");
        SLL = new CurrencyType("SLL");
        SOS = new CurrencyType("SOS");
        SRD = new CurrencyType("SRD");
        SSP = new CurrencyType("SSP");
        STD = new CurrencyType("STD");
        SYP = new CurrencyType("SYP");
        SZL = new CurrencyType("SZL");
        THB = new CurrencyType("THB");
        TJS = new CurrencyType("TJS");
        TMT = new CurrencyType("TMT");
        TND = new CurrencyType("TND");
        TOP = new CurrencyType("TOP");
        TRY = new CurrencyType("TRY");
        TTD = new CurrencyType("TTD");
        TWD = new CurrencyType("TWD");
        TZS = new CurrencyType("TZS");
        UAH = new CurrencyType("UAH");
        UGX = new CurrencyType("UGX");
        USD = new CurrencyType("USD");
        USN = new CurrencyType("USN");
        UYI = new CurrencyType("UYI");
        UYU = new CurrencyType("UYU");
        UZS = new CurrencyType("UZS");
        VEF = new CurrencyType("VEF");
        VND = new CurrencyType("VND");
        VUV = new CurrencyType("VUV");
        WST = new CurrencyType("WST");
        XAF = new CurrencyType("XAF");
        XAG = new CurrencyType("XAG");
        XAU = new CurrencyType("XAU");
        XBA = new CurrencyType("XBA");
        XBB = new CurrencyType("XBB");
        XBC = new CurrencyType("XBC");
        XBD = new CurrencyType("XBD");
        XCD = new CurrencyType("XCD");
        XDR = new CurrencyType("XDR");
        XFU = new CurrencyType("XFU");
        XOF = new CurrencyType("XOF");
        XPD = new CurrencyType("XPD");
        XPF = new CurrencyType("XPF");
        XPT = new CurrencyType("XPT");
        XSU = new CurrencyType("XSU");
        XTS = new CurrencyType("XTS");
        XUA = new CurrencyType("XUA");
        XXX = new CurrencyType("XXX");
        YER = new CurrencyType("YER");
        ZAR = new CurrencyType("ZAR");
        ZMW = currencyType = new CurrencyType("ZMW");
        CurrencyType[] arrcurrencyType = new CurrencyType[]{AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BOV, BRL, BSD, BTN, BWP, BYN, BYR, BZD, CAD, CDF, CHE, CHF, CHW, CLF, CLP, CNY, COP, COU, CRC, CUC, CUP, CVE, CZK, DJF, DKK, DOP, DZD, EGP, ERN, ETB, EUR, FJD, FKP, GBP, GEL, GHS, GIP, GMD, GNF, GTQ, GYD, HKD, HNL, HRK, HTG, HUF, IDR, ILS, INR, IQD, IRR, ISK, JMD, JOD, JPY, KES, KGS, KHR, KMF, KPW, KRW, KWD, KYD, KZT, LAK, LBP, LKR, LRD, LSL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRO, MUR, MVR, MWK, MXN, MXV, MYR, MZN, NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG, QAR, RON, RSD, RUB, RWF, SAR, SBD, SCR, SDG, SEK, SGD, SHP, SLL, SOS, SRD, SSP, STD, SYP, SZL, THB, TJS, TMT, TND, TOP, TRY, TTD, TWD, TZS, UAH, UGX, USD, USN, UYI, UYU, UZS, VEF, VND, VUV, WST, XAF, XAG, XAU, XBA, XBB, XBC, XBD, XCD, XDR, XFU, XOF, XPD, XPF, XPT, XSU, XTS, XUA, XXX, YER, ZAR, currencyType};
        $VALUES = arrcurrencyType;
    }

    private CurrencyType(String string3) {
        this.iso4217Code = string3;
    }

    public static CurrencyType getValue(String string2) {
        if (!TextUtils.isEmpty((CharSequence)string2)) {
            for (CurrencyType currencyType : CurrencyType.values()) {
                if (!currencyType.iso4217Code.equals((Object)string2)) continue;
                return currencyType;
            }
        }
        return null;
    }

    public static CurrencyType valueOf(String string2) {
        return (CurrencyType)Enum.valueOf(CurrencyType.class, (String)string2);
    }

    public static CurrencyType[] values() {
        return (CurrencyType[])$VALUES.clone();
    }

    public String toString() {
        return this.iso4217Code;
    }
}

